/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageReaderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_PAGE_READER = "page-reader-view";
var MIN_PAGE_WIDTH = 160;
var SWIPE_THRESHOLD_PX = 56;
var WHEEL_TURN_COOLDOWN_MS = 450;
var DEFAULT_SETTINGS = {
  fontSize: 18,
  lineHeight: 1.65,
  columnGap: 56,
  pagePadding: 34,
  theme: "paper",
  justifyText: false,
  hideFrontmatter: true,
  openInNewTab: true,
  turnPageWithVerticalScroll: false
};
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function getPercent(pageIndex, pageCount) {
  if (pageCount <= 1)
    return 0;
  return clamp(pageIndex / (pageCount - 1), 0, 1);
}
function stripYamlFrontmatter(markdown) {
  if (!markdown.startsWith("---"))
    return markdown;
  const match = markdown.match(/^---\s*\n[\s\S]*?\n---\s*(?:\n|$)/);
  return match ? markdown.slice(match[0].length).trimStart() : markdown;
}
function fileIdentityMatches(progress, file, pageCount) {
  return progress.fileMtime === file.stat.mtime && progress.fileSize === file.stat.size && progress.pageCount === pageCount;
}
var PageReaderPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.progress = {};
    this.lastFilePath = null;
    this.saveTimer = null;
  }
  async onload() {
    await this.loadPluginData();
    this.registerView(
      VIEW_TYPE_PAGE_READER,
      (leaf) => new PageReaderView(leaf, this)
    );
    this.addRibbonIcon("book-open", "Open active note in Page Reader", () => {
      void this.openActiveFileInReader();
    });
    this.addCommand({
      id: "open-active-note-in-page-reader",
      name: "Open active note in Page Reader",
      checkCallback: (checking) => {
        const file = this.getActiveMarkdownFile();
        if (!file)
          return false;
        if (!checking)
          void this.openReaderForFile(file);
        return true;
      }
    });
    this.addCommand({
      id: "resume-last-page-reader-note",
      name: "Resume last Page Reader note",
      callback: () => {
        void this.resumeLastReaderNote();
      }
    });
    this.addCommand({
      id: "reset-active-page-reader-progress",
      name: "Reset saved Page Reader progress for active note",
      checkCallback: (checking) => {
        const file = this.getActiveMarkdownFile();
        if (!file)
          return false;
        if (!checking) {
          this.resetProgress(file);
          new import_obsidian.Notice(`Page Reader progress reset for ${file.basename}`);
        }
        return true;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian.TFile) || file.extension !== "md")
          return;
        menu.addItem((item) => {
          item.setTitle("Open in Page Reader").setIcon("book-open").onClick(() => {
            void this.openReaderForFile(file);
          });
        });
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.handleRename(file, oldPath);
      })
    );
    this.addSettingTab(new PageReaderSettingTab(this.app, this));
  }
  async onunload() {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
      await this.savePluginData();
    }
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_PAGE_READER);
  }
  async loadPluginData() {
    var _a, _b, _c;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : {});
    this.progress = (_b = data == null ? void 0 : data.progress) != null ? _b : {};
    this.lastFilePath = (_c = data == null ? void 0 : data.lastFilePath) != null ? _c : null;
  }
  async savePluginData() {
    const data = {
      settings: this.settings,
      progress: this.progress,
      lastFilePath: this.lastFilePath
    };
    await this.saveData(data);
  }
  queueSaveData(delayMs = 300) {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
    }
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      void this.savePluginData();
    }, delayMs);
  }
  getActiveMarkdownFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile instanceof import_obsidian.TFile && activeFile.extension === "md") {
      return activeFile;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    const viewFile = activeView == null ? void 0 : activeView.file;
    if (viewFile instanceof import_obsidian.TFile && viewFile.extension === "md") {
      return viewFile;
    }
    return null;
  }
  getFileByPath(path) {
    if (!path)
      return null;
    const file = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(path));
    return file instanceof import_obsidian.TFile ? file : null;
  }
  async openActiveFileInReader() {
    const file = this.getActiveMarkdownFile();
    if (!file) {
      new import_obsidian.Notice("Open a Markdown note first, then run Page Reader.");
      return;
    }
    await this.openReaderForFile(file);
  }
  async openReaderForFile(file) {
    this.lastFilePath = file.path;
    this.queueSaveData();
    const workspace = this.app.workspace;
    const leaf = this.settings.openInNewTab ? workspace.getLeaf("tab") : workspace.getLeaf(false);
    await leaf.setViewState({
      type: VIEW_TYPE_PAGE_READER,
      state: { filePath: file.path },
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
  async resumeLastReaderNote() {
    var _a;
    const lastPath = (_a = this.lastFilePath) != null ? _a : this.getMostRecentProgressPath();
    const file = this.getFileByPath(lastPath);
    if (!file) {
      new import_obsidian.Notice("No saved Page Reader note yet.");
      return;
    }
    await this.openReaderForFile(file);
  }
  getMostRecentProgressPath() {
    const entries = Object.entries(this.progress);
    if (entries.length === 0)
      return null;
    entries.sort((a, b) => b[1].updatedAt - a[1].updatedAt);
    return entries[0][0];
  }
  getProgress(file) {
    return this.progress[file.path];
  }
  setProgress(file, pageIndex, pageCount) {
    this.progress[file.path] = {
      pageIndex: clamp(pageIndex, 0, Math.max(0, pageCount - 1)),
      pageCount,
      percent: getPercent(pageIndex, pageCount),
      updatedAt: Date.now(),
      fileMtime: file.stat.mtime,
      fileSize: file.stat.size
    };
    this.lastFilePath = file.path;
    this.queueSaveData();
  }
  resetProgress(file) {
    delete this.progress[file.path];
    this.queueSaveData();
  }
  clearAllProgress() {
    this.progress = {};
    this.queueSaveData();
  }
  refreshOpenReaders() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_PAGE_READER).forEach((leaf) => {
      if (leaf.view instanceof PageReaderView) {
        leaf.view.applySettingsAndRepaginate();
      }
    });
  }
  rerenderOpenReaders() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_PAGE_READER).forEach((leaf) => {
      if (leaf.view instanceof PageReaderView) {
        leaf.view.rerenderPreservingPosition();
      }
    });
  }
  handleRename(file, oldPath) {
    if (!(file instanceof import_obsidian.TFile))
      return;
    const progress = this.progress[oldPath];
    if (progress) {
      delete this.progress[oldPath];
      this.progress[file.path] = progress;
    }
    if (this.lastFilePath === oldPath) {
      this.lastFilePath = file.path;
    }
    if (progress || this.lastFilePath === file.path) {
      this.queueSaveData();
    }
  }
};
var PageReaderView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.file = null;
    this.filePath = null;
    this.pageIndex = 0;
    this.pageCount = 1;
    this.pageWidth = MIN_PAGE_WIDTH;
    this.pageHeight = 1;
    this.columnGap = DEFAULT_SETTINGS.columnGap;
    this.rootEl = null;
    this.titleEl = null;
    this.subtitleEl = null;
    this.stageEl = null;
    this.pagesEl = null;
    this.articleEl = null;
    this.pageIndicatorEl = null;
    this.percentEl = null;
    this.progressFillEl = null;
    this.previousButtonEl = null;
    this.nextButtonEl = null;
    this.resizeObserver = null;
    this.renderComponent = null;
    this.renderToken = 0;
    this.paginateTimer = null;
    this.progressTimer = null;
    this.reloadTimer = null;
    this.lastWheelTurnAt = 0;
    this.dragState = null;
    this.plugin = plugin;
    this.navigation = true;
    this.icon = "book-open";
  }
  getViewType() {
    return VIEW_TYPE_PAGE_READER;
  }
  getDisplayText() {
    return this.file ? `Read: ${this.file.basename}` : "Page Reader";
  }
  getState() {
    var _a;
    return {
      filePath: (_a = this.filePath) != null ? _a : void 0,
      pageIndex: this.pageIndex
    };
  }
  async setState(state, result) {
    await super.setState(state, result);
    if (typeof (state == null ? void 0 : state.filePath) === "string") {
      this.filePath = state.filePath;
      if (typeof state.pageIndex === "number") {
        this.pageIndex = state.pageIndex;
      }
      if (this.rootEl) {
        await this.loadFileByPath(state.filePath, state.pageIndex);
      }
    }
  }
  async onOpen() {
    var _a, _b;
    this.contentEl.empty();
    this.addAction("refresh-cw", "Refresh pages", () => {
      void this.renderCurrentFile({ requestedPage: this.pageIndex });
    });
    this.addAction("file-text", "Open source note", () => {
      void this.openSourceNote();
    });
    this.addAction("rotate-ccw", "Reset reading position", () => {
      this.resetCurrentProgress();
    });
    this.buildShell();
    this.registerEvents();
    const viewState = this.leaf.getViewState().state;
    const filePath = (_b = (_a = viewState == null ? void 0 : viewState.filePath) != null ? _a : this.filePath) != null ? _b : this.plugin.lastFilePath;
    const requestedPage = typeof (viewState == null ? void 0 : viewState.pageIndex) === "number" ? viewState.pageIndex : void 0;
    if (filePath) {
      await this.loadFileByPath(filePath, requestedPage);
    } else {
      this.renderEmptyState();
    }
  }
  async onClose() {
    this.persistProgressNow();
    this.unloadRenderComponent();
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
    this.clearTimers();
  }
  applySettingsAndRepaginate() {
    this.applyReaderSettings();
    this.queuePaginate(true);
  }
  rerenderPreservingPosition() {
    const percent = getPercent(this.pageIndex, this.pageCount);
    void this.renderCurrentFile({ requestedPercent: percent });
  }
  buildShell() {
    const root = this.contentEl.createDiv({ cls: "page-reader-root" });
    this.rootEl = root;
    const toolbar = root.createDiv({ cls: "page-reader-toolbar" });
    const titleWrap = toolbar.createDiv({ cls: "page-reader-title-wrap" });
    this.titleEl = titleWrap.createDiv({ cls: "page-reader-title", text: "Page Reader" });
    this.subtitleEl = titleWrap.createDiv({ cls: "page-reader-subtitle", text: "Choose a note to start reading" });
    const toolbarControls = toolbar.createDiv({ cls: "page-reader-toolbar-controls" });
    const sourceButton = toolbarControls.createEl("button", {
      cls: "page-reader-plain-button",
      text: "Source",
      attr: { type: "button", "aria-label": "Open source note" }
    });
    sourceButton.addEventListener("click", () => {
      void this.openSourceNote();
    });
    const resetButton = toolbarControls.createEl("button", {
      cls: "page-reader-plain-button",
      text: "Reset",
      attr: { type: "button", "aria-label": "Reset reading position" }
    });
    resetButton.addEventListener("click", () => {
      this.resetCurrentProgress();
    });
    const stage = root.createDiv({ cls: "page-reader-stage" });
    stage.tabIndex = 0;
    stage.setAttribute("role", "region");
    stage.setAttribute("aria-label", "Paged article reader");
    this.stageEl = stage;
    const pages = stage.createDiv({ cls: "page-reader-pages" });
    this.pagesEl = pages;
    const article = pages.createDiv({ cls: "page-reader-article markdown-preview-view markdown-rendered" });
    this.articleEl = article;
    const previousHit = stage.createEl("button", {
      cls: "page-reader-edge-button page-reader-edge-button-left",
      text: "\u2039",
      attr: { type: "button", "aria-label": "Previous page" }
    });
    previousHit.addEventListener("click", () => this.previousPage());
    const nextHit = stage.createEl("button", {
      cls: "page-reader-edge-button page-reader-edge-button-right",
      text: "\u203A",
      attr: { type: "button", "aria-label": "Next page" }
    });
    nextHit.addEventListener("click", () => this.nextPage());
    const footer = root.createDiv({ cls: "page-reader-footer" });
    this.previousButtonEl = footer.createEl("button", {
      cls: "page-reader-nav-button",
      text: "\u2190 Previous",
      attr: { type: "button" }
    });
    this.previousButtonEl.addEventListener("click", () => this.previousPage());
    const progressWrap = footer.createDiv({ cls: "page-reader-progress-wrap" });
    const progressMeta = progressWrap.createDiv({ cls: "page-reader-progress-meta" });
    this.pageIndicatorEl = progressMeta.createSpan({ cls: "page-reader-page-indicator", text: "Page 1 of 1" });
    this.percentEl = progressMeta.createSpan({ cls: "page-reader-percent", text: "0%" });
    const progressTrack = progressWrap.createDiv({ cls: "page-reader-progress-track" });
    this.progressFillEl = progressTrack.createDiv({ cls: "page-reader-progress-fill" });
    this.nextButtonEl = footer.createEl("button", {
      cls: "page-reader-nav-button page-reader-nav-button-primary",
      text: "Next \u2192",
      attr: { type: "button" }
    });
    this.nextButtonEl.addEventListener("click", () => this.nextPage());
    this.applyReaderSettings();
  }
  registerEvents() {
    if (!this.stageEl)
      return;
    this.registerDomEvent(this.stageEl, "keydown", (event) => this.handleKeydown(event));
    this.registerDomEvent(this.stageEl, "click", () => {
      var _a;
      return (_a = this.stageEl) == null ? void 0 : _a.focus();
    });
    this.registerDomEvent(this.stageEl, "wheel", (event) => this.handleWheel(event), { passive: false });
    this.registerDomEvent(this.stageEl, "pointerdown", (event) => this.handlePointerDown(event));
    this.registerDomEvent(this.stageEl, "pointermove", (event) => this.handlePointerMove(event));
    this.registerDomEvent(this.stageEl, "pointerup", (event) => this.handlePointerUp(event));
    this.registerDomEvent(this.stageEl, "pointercancel", (event) => this.handlePointerCancel(event));
    this.resizeObserver = new ResizeObserver(() => this.queuePaginate(true));
    this.resizeObserver.observe(this.stageEl);
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && file.path === this.filePath) {
          this.queueReload();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file.path === this.filePath) {
          this.file = null;
          this.filePath = null;
          this.renderMissingState("This note was deleted.");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (oldPath === this.filePath && file instanceof import_obsidian.TFile) {
          this.file = file;
          this.filePath = file.path;
          this.updateHeader();
          this.queueReload();
        }
      })
    );
  }
  async loadFileByPath(filePath, requestedPage) {
    const file = this.plugin.getFileByPath(filePath);
    if (!file || file.extension !== "md") {
      this.file = null;
      this.filePath = filePath;
      this.renderMissingState("Page Reader could not find that Markdown note.");
      return;
    }
    this.file = file;
    this.filePath = file.path;
    this.plugin.lastFilePath = file.path;
    this.plugin.queueSaveData();
    await this.renderCurrentFile({ requestedPage });
  }
  async renderCurrentFile(options = {}) {
    var _a;
    if (!this.file || !this.articleEl) {
      this.renderEmptyState();
      return;
    }
    const token = ++this.renderToken;
    const file = this.file;
    const priorPercent = getPercent(this.pageIndex, this.pageCount);
    this.applyReaderSettings();
    this.unloadRenderComponent();
    this.updateHeader("Loading\u2026");
    this.articleEl.empty();
    this.articleEl.addClass("is-loading");
    this.articleEl.createDiv({ cls: "page-reader-loading", text: "Preparing pages\u2026" });
    try {
      const rawMarkdown = await this.app.vault.read(file);
      if (token !== this.renderToken)
        return;
      const markdown = this.plugin.settings.hideFrontmatter ? stripYamlFrontmatter(rawMarkdown) : rawMarkdown;
      const renderComponent = new import_obsidian.Component();
      const renderContainer = document.createElement("div");
      this.addChild(renderComponent);
      this.renderComponent = renderComponent;
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, renderContainer, file.path, renderComponent);
      if (token !== this.renderToken) {
        if (this.renderComponent === renderComponent) {
          this.unloadRenderComponent();
        } else {
          renderComponent.unload();
        }
        return;
      }
      this.articleEl.empty();
      this.articleEl.removeClass("is-loading");
      while (renderContainer.firstChild) {
        this.articleEl.appendChild(renderContainer.firstChild);
      }
      this.prepareRenderedContent();
      await this.nextAnimationFrame();
      if (token !== this.renderToken)
        return;
      this.recalculatePages();
      const requestedPage = options.requestedPage;
      const requestedPercent = (_a = options.requestedPercent) != null ? _a : priorPercent;
      const restoredPage = this.getInitialPage(file, requestedPage, requestedPercent);
      this.goToPage(restoredPage, { animate: false, save: false });
      this.updateHeader();
      this.persistProgressSoon();
    } catch (error) {
      console.error("Page Reader failed to render", error);
      this.renderMissingState("Page Reader could not render this note.");
      new import_obsidian.Notice("Page Reader could not render this note. Check the developer console for details.");
    }
  }
  prepareRenderedContent() {
    if (!this.articleEl)
      return;
    this.articleEl.querySelectorAll("img").forEach((image) => {
      image.setAttribute("draggable", "false");
      image.addEventListener("load", () => this.queuePaginate(true), { once: true });
    });
    this.articleEl.querySelectorAll("a").forEach((link) => {
      link.addEventListener("click", (event) => {
        event.stopPropagation();
      });
    });
  }
  getInitialPage(file, requestedPage, requestedPercent) {
    if (typeof requestedPage === "number") {
      return clamp(Math.round(requestedPage), 0, Math.max(0, this.pageCount - 1));
    }
    const progress = this.plugin.getProgress(file);
    if (!progress) {
      return clamp(Math.round(requestedPercent * (this.pageCount - 1)), 0, Math.max(0, this.pageCount - 1));
    }
    if (fileIdentityMatches(progress, file, this.pageCount)) {
      return clamp(progress.pageIndex, 0, Math.max(0, this.pageCount - 1));
    }
    return clamp(Math.round(progress.percent * (this.pageCount - 1)), 0, Math.max(0, this.pageCount - 1));
  }
  recalculatePages() {
    if (!this.pagesEl || !this.articleEl)
      return;
    const padding = this.plugin.settings.pagePadding;
    const width = Math.max(MIN_PAGE_WIDTH, Math.floor(this.pagesEl.clientWidth - padding * 2));
    const height = Math.max(1, Math.floor(this.pagesEl.clientHeight - padding * 2));
    const gap = this.plugin.settings.columnGap;
    this.pageWidth = width;
    this.pageHeight = height;
    this.columnGap = gap;
    this.articleEl.style.width = `${width}px`;
    this.articleEl.style.height = `${height}px`;
    this.articleEl.style.columnWidth = `${width}px`;
    this.articleEl.style.columnGap = `${gap}px`;
    const totalWidth = Math.max(width, this.articleEl.scrollWidth);
    this.pageCount = Math.max(1, Math.round((totalWidth + gap) / (width + gap)));
    this.pageIndex = clamp(this.pageIndex, 0, this.pageCount - 1);
    this.updateTransform(false);
    this.updateProgressUi();
  }
  queuePaginate(preservePosition) {
    if (this.paginateTimer !== null) {
      window.clearTimeout(this.paginateTimer);
    }
    const percent = getPercent(this.pageIndex, this.pageCount);
    this.paginateTimer = window.setTimeout(() => {
      this.paginateTimer = null;
      this.recalculatePages();
      if (preservePosition) {
        const restoredPage = Math.round(percent * (this.pageCount - 1));
        this.goToPage(restoredPage, { animate: false, save: true });
      }
    }, 80);
  }
  goToPage(pageIndex, options) {
    const nextPage = clamp(Math.round(pageIndex), 0, Math.max(0, this.pageCount - 1));
    const didChange = nextPage !== this.pageIndex;
    this.pageIndex = nextPage;
    this.updateTransform(options.animate);
    this.updateProgressUi();
    if (options.save && (didChange || this.file)) {
      this.persistProgressSoon();
    }
  }
  nextPage() {
    if (this.pageIndex >= this.pageCount - 1)
      return;
    this.goToPage(this.pageIndex + 1, { animate: true, save: true });
  }
  previousPage() {
    if (this.pageIndex <= 0)
      return;
    this.goToPage(this.pageIndex - 1, { animate: true, save: true });
  }
  updateTransform(animate, dragOffset = 0) {
    if (!this.articleEl)
      return;
    const x = -this.pageIndex * (this.pageWidth + this.columnGap) + dragOffset;
    this.articleEl.toggleClass("is-turning", animate);
    this.articleEl.style.transform = `translate3d(${x}px, 0, 0)`;
  }
  updateProgressUi() {
    var _a, _b;
    const humanPage = Math.min(this.pageIndex + 1, this.pageCount);
    const percent = getPercent(this.pageIndex, this.pageCount);
    const percentLabel = `${Math.round(percent * 100)}%`;
    (_a = this.pageIndicatorEl) == null ? void 0 : _a.setText(`Page ${humanPage} of ${this.pageCount}`);
    (_b = this.percentEl) == null ? void 0 : _b.setText(percentLabel);
    if (this.progressFillEl) {
      this.progressFillEl.style.width = `${percent * 100}%`;
    }
    if (this.previousButtonEl) {
      this.previousButtonEl.disabled = this.pageIndex <= 0;
    }
    if (this.nextButtonEl) {
      this.nextButtonEl.disabled = this.pageIndex >= this.pageCount - 1;
    }
  }
  updateHeader(status) {
    var _a, _b, _c, _d;
    if (!this.file) {
      (_a = this.titleEl) == null ? void 0 : _a.setText("Page Reader");
      (_b = this.subtitleEl) == null ? void 0 : _b.setText(status != null ? status : "Choose a note to start reading");
      return;
    }
    (_c = this.titleEl) == null ? void 0 : _c.setText(this.file.basename);
    (_d = this.subtitleEl) == null ? void 0 : _d.setText(status != null ? status : this.file.path);
  }
  applyReaderSettings() {
    if (!this.rootEl || !this.articleEl)
      return;
    const settings = this.plugin.settings;
    this.rootEl.dataset.theme = settings.theme;
    this.rootEl.toggleClass("is-justified", settings.justifyText);
    this.rootEl.style.setProperty("--page-reader-font-size", `${settings.fontSize}px`);
    this.rootEl.style.setProperty("--page-reader-line-height", settings.lineHeight.toString());
    this.rootEl.style.setProperty("--page-reader-padding", `${settings.pagePadding}px`);
    this.rootEl.style.setProperty("--page-reader-gap", `${settings.columnGap}px`);
  }
  renderEmptyState() {
    this.unloadRenderComponent();
    this.file = null;
    this.filePath = null;
    this.pageIndex = 0;
    this.pageCount = 1;
    this.updateHeader();
    if (!this.articleEl)
      return;
    this.articleEl.empty();
    this.articleEl.removeClass("is-loading");
    this.articleEl.createDiv({ cls: "page-reader-empty-icon", text: "\u{1F4D6}" });
    this.articleEl.createEl("h2", { text: "Open a note in Page Reader" });
    this.articleEl.createEl("p", {
      text: "Use the ribbon icon, command palette, or a note\u2019s file menu to read long articles one page at a time."
    });
    const openButton = this.articleEl.createEl("button", {
      cls: "mod-cta page-reader-empty-button",
      text: "Open active note",
      attr: { type: "button" }
    });
    openButton.addEventListener("click", () => {
      void this.plugin.openActiveFileInReader();
    });
    this.recalculatePages();
  }
  renderMissingState(message) {
    this.unloadRenderComponent();
    this.pageIndex = 0;
    this.pageCount = 1;
    this.updateHeader(message);
    if (!this.articleEl)
      return;
    this.articleEl.empty();
    this.articleEl.removeClass("is-loading");
    this.articleEl.createDiv({ cls: "page-reader-empty-icon", text: "\u26A0\uFE0F" });
    this.articleEl.createEl("h2", { text: "Cannot open note" });
    this.articleEl.createEl("p", { text: message });
    this.recalculatePages();
  }
  handleKeydown(event) {
    if (event.defaultPrevented)
      return;
    const key = event.key;
    if (key === "ArrowRight" || key === "PageDown" || key === " " && !event.shiftKey) {
      event.preventDefault();
      this.nextPage();
    } else if (key === "ArrowLeft" || key === "PageUp" || key === " " && event.shiftKey) {
      event.preventDefault();
      this.previousPage();
    } else if (key === "Home") {
      event.preventDefault();
      this.goToPage(0, { animate: true, save: true });
    } else if (key === "End") {
      event.preventDefault();
      this.goToPage(this.pageCount - 1, { animate: true, save: true });
    }
  }
  handleWheel(event) {
    const absX = Math.abs(event.deltaX);
    const absY = Math.abs(event.deltaY);
    const horizontalTurn = absX > absY && absX > 24;
    const verticalTurn = this.plugin.settings.turnPageWithVerticalScroll && absY > absX && absY > 36;
    if (!horizontalTurn && !verticalTurn)
      return;
    const now = Date.now();
    if (now - this.lastWheelTurnAt < WHEEL_TURN_COOLDOWN_MS) {
      event.preventDefault();
      return;
    }
    this.lastWheelTurnAt = now;
    event.preventDefault();
    const delta = horizontalTurn ? event.deltaX : event.deltaY;
    if (delta > 0) {
      this.nextPage();
    } else {
      this.previousPage();
    }
  }
  handlePointerDown(event) {
    var _a, _b;
    const target = event.target;
    if (target == null ? void 0 : target.closest("a, button, input, textarea, select"))
      return;
    if (event.button !== 0)
      return;
    this.dragState = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startY: event.clientY,
      lastX: event.clientX,
      lastY: event.clientY,
      startedAt: Date.now(),
      dragging: false
    };
    (_a = this.stageEl) == null ? void 0 : _a.setPointerCapture(event.pointerId);
    (_b = this.stageEl) == null ? void 0 : _b.focus();
  }
  handlePointerMove(event) {
    if (!this.dragState || this.dragState.pointerId !== event.pointerId)
      return;
    this.dragState.lastX = event.clientX;
    this.dragState.lastY = event.clientY;
    const dx = event.clientX - this.dragState.startX;
    const dy = event.clientY - this.dragState.startY;
    if (!this.dragState.dragging) {
      if (Math.abs(dx) < 12 || Math.abs(dx) < Math.abs(dy))
        return;
      this.dragState.dragging = true;
    }
    event.preventDefault();
    const atStart = this.pageIndex <= 0 && dx > 0;
    const atEnd = this.pageIndex >= this.pageCount - 1 && dx < 0;
    const dampedDx = atStart || atEnd ? dx * 0.28 : dx;
    this.updateTransform(false, dampedDx);
  }
  handlePointerUp(event) {
    var _a;
    if (!this.dragState || this.dragState.pointerId !== event.pointerId)
      return;
    const dragState = this.dragState;
    this.dragState = null;
    (_a = this.stageEl) == null ? void 0 : _a.releasePointerCapture(event.pointerId);
    const dx = event.clientX - dragState.startX;
    const dy = event.clientY - dragState.startY;
    const duration = Date.now() - dragState.startedAt;
    const velocity = Math.abs(dx) / Math.max(1, duration);
    const shouldTurn = Math.abs(dx) > SWIPE_THRESHOLD_PX && Math.abs(dx) > Math.abs(dy);
    const quickFlick = Math.abs(dx) > 28 && velocity > 0.6 && Math.abs(dx) > Math.abs(dy);
    if (shouldTurn || quickFlick) {
      if (dx < 0) {
        this.nextPage();
      } else {
        this.previousPage();
      }
    } else {
      this.updateTransform(true);
    }
  }
  handlePointerCancel(event) {
    var _a;
    if (!this.dragState || this.dragState.pointerId !== event.pointerId)
      return;
    this.dragState = null;
    (_a = this.stageEl) == null ? void 0 : _a.releasePointerCapture(event.pointerId);
    this.updateTransform(true);
  }
  queueReload() {
    if (this.reloadTimer !== null) {
      window.clearTimeout(this.reloadTimer);
    }
    const percent = getPercent(this.pageIndex, this.pageCount);
    this.reloadTimer = window.setTimeout(() => {
      this.reloadTimer = null;
      void this.renderCurrentFile({ requestedPercent: percent });
    }, 350);
  }
  persistProgressSoon() {
    if (this.progressTimer !== null) {
      window.clearTimeout(this.progressTimer);
    }
    this.progressTimer = window.setTimeout(() => {
      this.progressTimer = null;
      this.persistProgressNow();
    }, 250);
  }
  persistProgressNow() {
    if (this.progressTimer !== null) {
      window.clearTimeout(this.progressTimer);
      this.progressTimer = null;
    }
    if (!this.file)
      return;
    this.plugin.setProgress(this.file, this.pageIndex, this.pageCount);
  }
  resetCurrentProgress() {
    if (!this.file)
      return;
    this.plugin.resetProgress(this.file);
    this.goToPage(0, { animate: true, save: false });
    new import_obsidian.Notice(`Page Reader progress reset for ${this.file.basename}`);
  }
  async openSourceNote() {
    if (!this.file)
      return;
    const workspace = this.app.workspace;
    const leaf = workspace.getLeaf("tab");
    await leaf.openFile(this.file);
    this.app.workspace.revealLeaf(leaf);
  }
  nextAnimationFrame() {
    return new Promise((resolve) => {
      window.requestAnimationFrame(() => resolve());
    });
  }
  unloadRenderComponent() {
    if (!this.renderComponent)
      return;
    this.removeChild(this.renderComponent);
    this.renderComponent = null;
  }
  clearTimers() {
    if (this.paginateTimer !== null) {
      window.clearTimeout(this.paginateTimer);
      this.paginateTimer = null;
    }
    if (this.progressTimer !== null) {
      window.clearTimeout(this.progressTimer);
      this.progressTimer = null;
    }
    if (this.reloadTimer !== null) {
      window.clearTimeout(this.reloadTimer);
      this.reloadTimer = null;
    }
  }
};
var PageReaderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Page Reader" });
    containerEl.createEl("p", {
      text: "Tune the paged reading experience for long notes and saved articles."
    });
    new import_obsidian.Setting(containerEl).setName("Reader theme").setDesc("Choose the page background used inside Page Reader.").addDropdown(
      (dropdown) => dropdown.addOption("obsidian", "Match Obsidian").addOption("paper", "Paper").addOption("sepia", "Sepia").addOption("night", "Night").setValue(this.plugin.settings.theme).onChange(async (value) => {
        this.plugin.settings.theme = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Font size").setDesc("Article text size in pixels.").addSlider(
      (slider) => slider.setLimits(14, 28, 1).setDynamicTooltip().setValue(this.plugin.settings.fontSize).onChange(async (value) => {
        this.plugin.settings.fontSize = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Line height").setDesc("Spacing between lines.").addSlider(
      (slider) => slider.setLimits(1.2, 2, 0.05).setDynamicTooltip().setValue(this.plugin.settings.lineHeight).onChange(async (value) => {
        this.plugin.settings.lineHeight = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Page padding").setDesc("Whitespace around every page.").addSlider(
      (slider) => slider.setLimits(16, 72, 2).setDynamicTooltip().setValue(this.plugin.settings.pagePadding).onChange(async (value) => {
        this.plugin.settings.pagePadding = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Page turn gap").setDesc("Horizontal space between virtual pages.").addSlider(
      (slider) => slider.setLimits(24, 120, 4).setDynamicTooltip().setValue(this.plugin.settings.columnGap).onChange(async (value) => {
        this.plugin.settings.columnGap = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Justify article text").setDesc("Align both edges of paragraph text, like many ebooks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.justifyText).onChange(async (value) => {
        this.plugin.settings.justifyText = value;
        await this.plugin.savePluginData();
        this.plugin.refreshOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hide YAML frontmatter").setDesc("Remove frontmatter from the reader view so articles start at the title/body.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hideFrontmatter).onChange(async (value) => {
        this.plugin.settings.hideFrontmatter = value;
        await this.plugin.savePluginData();
        this.plugin.rerenderOpenReaders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open reader in a new tab").setDesc("Keep your source note open and launch Page Reader beside it.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openInNewTab).onChange(async (value) => {
        this.plugin.settings.openInNewTab = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Vertical wheel turns pages").setDesc("Let a regular mouse wheel move between pages. Trackpad horizontal swipes always work.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.turnPageWithVerticalScroll).onChange(async (value) => {
        this.plugin.settings.turnPageWithVerticalScroll = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Clear saved reading positions").setDesc("Forget every saved page position for Page Reader.").addButton(
      (button) => button.setButtonText("Clear").setWarning().onClick(async () => {
        this.plugin.clearAllProgress();
        await this.plugin.savePluginData();
        new import_obsidian.Notice("Page Reader positions cleared.");
      })
    );
  }
};
